project:
  type: website
  output-dir: _site
  execute-dir: project
  resources: scripts

website:
  title: "MA [46]15 Final Project - Group 1"
  navbar:
    right:
      - about.qmd
      - big_picture.qmd
      - analysis.qmd
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css



