project:
  type: website
  output-dir: _site
  execute-dir: project
  resources:  
    dataset
    cleaned_dataset_full.rds
  
website:
  title: "Road Real Talk: Crashes, Conditions, and Rescue"
  navbar:
    right:
      - about.qmd
      - big_picture.qmd
      - analysis.qmd
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css
  
